version: '3'

services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
  redis:
    image: redis:6-alpine

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      SECRET_KEY_BASE: "c77a076a8f1c0ce5618a27f5bc0a2f6fc69ab80d4339f769555841bb31f6cd2904a2f063c4e572214a64368c34f55f58a1fabbbb007771ac397f8efa368891a3"
      DATABASE_URL: postgres://postgres@db:5432/fair_pair
      REDIS_URL: redis://redis:6379/0
